web_application/service_requests/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
# from django.contrib.auth.views import ProfileView
urlpatterns = [
    path('register/', views.register, name='register'),
    path('submit/', views.submit_request, name='submit_request'),
    path('track/', views.track_requests, name='track_requests'),
    path('submit_success/', views.submit_success, name='submit_success'),
    path('login/', LoginView.as_view(), name='login'),
    #  path('accounts/profile/', ProfileView.as_view(), name='profile'),
]

web_application/web_application/urls.py
from django.contrib import admin
from django.urls import path,include
from service_requests import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service_requests.urls')),
]

web_application/crud/models.py
from django.db import models

class Employee(models.Model):
	eid = models.CharField(max_length=10)
	ename = models.CharField(max_length=50)
	eemail = models.EmailField()
	econtact = models.CharField(max_length=10)

	class Meta:
		db_table = "employee"
		

	def __str__(self):
		return self.ename

web_application/service_requests/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.contrib.auth.models import User

class ServiceRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    request_type = models.CharField(max_length=100)
    details = models.TextField()
    attachment = models.FileField(upload_to='attachments/', null=True, blank=True)
    status = models.CharField(max_length=50, default='Pending')
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add additional user profile fields as needed

web_application/crud/forms.py
from django import forms
from crud.models import Employee

class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = "__all__"

web_application/service_requests/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ServiceRequest

class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['request_type', 'details', 'attachment']

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

web_application/crud/views.py
from django.shortcuts import render,redirect
from crud.forms import EmployeeForm
from crud.models import Employee

def emp(request):
	if request.method == "POST":
		form = EmployeeForm (request.POST) # here "form" is one varible
		
		if form.is_valid():
			try:
				form.save()
    			
				return redirect("/show")
			except:
       
				pass
	else:
		form = EmployeeForm()
	return render(request,"index.html",{'form':form})

def show(request):
	employees = Employee.objects.all() # it's select query,select all data store in employees varible
	return render(request,"show.html",{'employees': employees})

def edit(request,id):
	employee = Employee.objects.get(id=id)
	return render(request,"edit.html",{'employee':employee})

def update(request,id):
	employee = Employee.objects.get(id=id)
	form = EmployeeForm(request.POST, instance=employee)
	if form.is_valid():
		form.save()
		return redirect('/show')
	return render(request,"edit.html",{'employee':employee})

def delete(request,id):
	employee = Employee.objects.get(id=id)
	employee.delete()
	return redirect("/show")

def home(request):
	return render(request,"home.html")

web_application/service_requests/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .forms import ServiceRequestForm, UserRegistrationForm
from .models import ServiceRequest

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form})

def submit_request(request):
    if request.method == 'POST':
        form = ServiceRequestForm(request.POST, request.FILES)
        if form.is_valid():
            service_request = form.save(commit=False)
            service_request.user = request.user
            service_request.save()
            return redirect('submit_success')
    else:
        form = ServiceRequestForm()
    return render(request, 'submit_request.html', {'form': form})

def track_requests(request):
    service_requests = ServiceRequest.objects.filter(user=request.user)
    return render(request, 'track_requests.html', {'service_requests': service_requests})

def submit_success(request):
    return render(request, 'submit_success.html')

web_application/crud/templates/edit.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	{% comment %} {% load staticfiles %} {% endcomment %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	{% comment %} <!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> --> {% endcomment %}
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Update Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee ID : </label>
			<div class="col-sm-4">
				<input type="text" name="eid" id="id_eid" value="{{ employee.eid }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Name : </label>
			<div class="col-sm-4">
				<input type="text" name="ename" id="id_ename" value="{{ employee.ename }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Email : </label>
			<div class="col-sm-4">
				<input type="text" name="eemail" id="id_eemail" value="{{ employee.eemail }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Contact : </label>
			<div class="col-sm-4">
				<input type="text" name="econtact" id="id_econtact" value="{{ employee.econtact }}"/>
			</div>
		</div>
		<button type="submit" class="btn btn-success">Update</button>
	</div>

</form>
</body>
</html>

web_application/crud/templates/home.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<!-- <nav>
	<ul>
		<li><a href="" class="btn btn-primary">Home</a></li>
		<li><a href="/emp" class="btn btn-primary">Add New Record</a></li>
		<li><a href="/show" class="btn btn-primary">Show</a></li>
	</ul>
</nav> -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/emp">Add New Record</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/show">Show</span></a>
      </li>
    </ul>
    
  </div>
</nav>

web_application/crud/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	{% comment %} {% load staticfiles %} {% endcomment %}
	{% comment %} <!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> --> {% endcomment %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
<form method="POST" class="post-form" action="/emp">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Enter Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee ID : </label>
			<div class="col-sm-4">
				{{ form.eid }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Name : </label>
			<div class="col-sm-4">
				{{ form.ename }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Email : </label>
			<div class="col-sm-4">
				{{ form.eemail }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Contact : </label>
			<div class="col-sm-4">
				{{ form.econtact }}
			</div>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

</form>
</body>
</html>

web_application/crud/templates/show.html
<!DOCTYPE html>
<html>
<head>
	<title>Employee Record</title>
		{% comment %} {% load staticfiles %} {% endcomment %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	{% comment %} <!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> --> {% endcomment %}
</head>
<body>
	<div class="container">
	<table class="table table-striped table-bordered table-sm">
		<thead class="thead-dark">
			<tr>
				<th>Employee ID</th>
				<th>Employee Name</th>
				<th>Employee Email</th>
				<th>Employee Contact</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for employee in employees %}
			<tr>
				<td>{{ employee.eid }}</td>
				<td>{{ employee.ename }}</td>
				<td>{{ employee.eemail }}</td>
				<td>{{ employee.econtact }}</td>
				<td>
					<a href="/edit/{{ employee.id}}"><span class="glyphicon glyphicon-pencil">Edit</span></a> | 
					<a href="/delete/{{ employee.id}}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</div>
</body>
</html>

web_application/service_requests/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2>User Registration</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
    <!-- Include Bootstrap JS (optional) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

web_application/service_requests/templates/service_requests/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gas Utility Service{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Gas Utility Service</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'service_requests:submit_request' %}">Submit Request</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'service_requests:track_request' %}">Track Requests</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS (optional) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+

web_application/service_requests/templates/service_requests/submit_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit Service Request</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2>Submit Service Request</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>
</html>

web_application/service_requests/templates/service_requests/submit_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submission Successful</title>
    <!-- Add any additional CSS or meta tags here -->
</head>
<body>
    <div class="container">
        <h2>Submission Successful</h2>
        <p>Your service request has been successfully submitted.</p>
        <!-- You can add more content or links here as needed -->
    </div>
</body>
</html>

web_application/service_requests/templates/service_requests/track_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Track Service Requests</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2>Track Service Requests</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Request Type</th>
                    <th>Details</th>
                    <th>Status</th>
                    <th>Submitted At</th>
                    <th>Resolved At</th>
                </tr>
            </thead>
            <tbody>
                {% for request in requests %}
                <tr>
                    <td>{{ request.request_type }}</td>
                    <td>{{ request.details }}</td>
                    <td>{{ request.status }}</td>
                    <td>{{ request.submitted_at }}</td>
                    <td>{{ request.resolved_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

web_application/service_requests/templates/submit_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Request Submission</title>
</head>
<body>
    <h2>Service Request Submission</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

web_application/service_requests/templates/submit_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submission Successful</title>
</head>
<body>
    <h2>Submission Successful</h2>
    <p>Your service request has been successfully submitted.</p>
</body>
</html>

web_application/service_requests/templates/track_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Track Service Requests</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h2>Track Service Requests</h2>
    {% if service_requests %}
        <table>
            <tr>
                <th>Request Type</th>
                <th>Status</th>
                <th>Details</th>
                <th>Attachment</th>
                <th>Submitted At</th>
                <th>Resolved At</th>
                <th>User Profile</th>
            </tr>
            {% for request in service_requests %}
                <tr>
                    <td>{{ request.request_type }}</td>
                    <td>{{ request.status }}</td>
                    <td>{{ request.details }}</td>
                    {% comment %} <td><a href="{{ MEDIA_URL }}{{ request.attachment }}">{{ request.attachment }}</a></td> {% endcomment %}
                    <td>{{ request.submitted_at }}</td>
                    <td>{{ request.resolved_at }}</td>
                    <td>{{ request.user_id }}</td> <!-- Assuming UserProfile model has __str__ method defined -->
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No service requests found.</p>
    {% endif %}
</body>